site_name: SAE601
site_url: https://nformichella.pages.gitlab.rt.lan/kube-dep
repo_url: https://gitlab.rt.lan/nformichella/kube-dep
repo_name: SAE601
nav:
  - Introduction: index.md
  - GitOps: git.md
  - Kubernetes: kube.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - search.suggest
    - search.highlight
  language: fr
extra:
  consent:
    title: Cookie consent
    description: >-

      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
plugins:
  - search
