{
 "title": "APP",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prod diamant",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_attente_prod_diamant_queue",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre (STAGING)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\"file_attente_staging_.*_queue\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Nombre (DEV)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{__name__=~\"file_attente_dev_.*_queue\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Nombre (PROD)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{__name__=~\"file_attente_prod_.*_queue\"}",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}