discriminator: "queueapp-base-{{ target.name }}"

targets:
  - name: staging
    context: staging
    args:
      base_domain: 192-168-1-200.nip.io
    images:
      - image: traefik
        resultImage: traefik:2.11
  - name: prod
    context: prod
    args:
      base_domain: 192-168-1-205.nip.io
    images:
      - image: traefik
        resultImage: traefik:2.10
